# Generated by Django 4.2.23 on 2025-06-15 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('days_applicable', models.JSONField(help_text="List of days like ['Mon', 'Tue']")),
                ('distance_base_price', models.FloatField()),
                ('distance_base_km', models.FloatField()),
                ('distance_additional_price', models.FloatField()),
                ('waiting_charge', models.FloatField(help_text='Per 3 mins')),
                ('free_waiting_minutes', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeMultiplierTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_minute', models.IntegerField()),
                ('to_minute', models.IntegerField()),
                ('multiplier', models.FloatField()),
                ('pricing_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_multipliers', to='pricing.pricingconfig')),
            ],
            options={
                'ordering': ['from_minute'],
            },
        ),
        migrations.CreateModel(
            name='ConfigLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.pricingconfig')),
            ],
        ),
    ]
